export const dataSlides = [
  {
    id: 1,
    title: "Limited Edition For Home Interior Design",
    tagline: "EXTRA -10% OFF WITH CODE: HOOKER001",
    image: "/image/L01-media-01.webp",
  },
  {
    id: 2,
    title: "Furnish Your Dream With Our Furniture",
    tagline: "EXTRA -10% OFF WITH CODE: HOOKER001",
    image: "/image/L01-media-02.webp",
  },
];

export const dataCategories = [
  {
    id: 1,
    image: "/image/L01-category-01.webp",
    title: "Table & chair",
    count: 8,
  },
  {
    id: 2,
    image: "/image/L01-category-02.webp",
    title: "Ceramic Art",
    count: 8,
  },
  {
    id: 3,
    image: "/image/L01-category-03.webp",
    title: "Lighting",
    count: 8,
  },
  {
    id: 4,
    image: "/image/L01-category-04.webp",
    title: "Sofa & chair",
    count: 8,
  },
  {
    id: 5,
    image: "/image/L01-category-01.webp",
    title: "Table & chair",
    count: 8,
  },
  {
    id: 6,
    image: "/image/L01-category-02.webp",
    title: "Ceramic Art",
    count: 8,
  },
  {
    id: 7,
    image: "/image/L01-category-03.webp",
    title: "Lighting",
    count: 8,
  },
  {
    id: 8,
    image: "/image/L01-category-04.webp",
    title: "Sofa & chair",
    count: 8,
  },
];

export const FurnitureTrending = [
  {
    id: "1",
    image: "/image/furniture-01.jpg",
    imageHover: "/image/furniture-01-02.jpg",
    title: "Field Lounge Chair",
    originalPrice: 200,
    salePrice: 150,
    bestSelling: 5,
    date: "2023-07-01",
    available: 8,
    feature: true,
    type: "Home",
  },
  {
    id: "2",
    image: "/image/furniture-02.jpg",
    imageHover: "/image/furniture-02-02.jpg",
    title: "Peek 1 Door 3 Drawer Credenza",
    originalPrice: 150,
    salePrice: 130,
    bestSelling: 3,
    date: "2023-06-15",
    available: 5,
    feature: false,
    type: "Home",
  },
  {
    id: "3",
    image: "/image/furniture-03.jpg",
    imageHover: "/image/furniture-03-02.jpg",
    title: "Bully Table Lamp",
    originalPrice: 350,
    salePrice: 250,
    bestSelling: 8,
    date: "2023-05-20",
    available: 12,
    feature: true,
    type: "Home",
  },
  {
    id: "4",
    image: "/image/furniture-04.jpg",
    imageHover: "/image/furniture-04-02.jpg",
    title: "Bobber Table Lamp",
    originalPrice: 350,
    salePrice: 320,
    bestSelling: 7,
    date: "2023-07-10",
    available: 3,
    feature: false,
    type: "Home",
  },
  {
    id: "5",
    image: "/image/furniture-05.jpg",
    imageHover: "/image/furniture-05-02.jpg",
    title: "Half Past Large Side Table",
    originalPrice: 200,
    salePrice: 180,
    bestSelling: 6,
    date: "2023-08-05",
    available: 7,
    feature: true,
    type: "Home",
  },
  {
    id: "6",
    image: "/image/furniture-06.jpg",
    imageHover: "/image/furniture-06-02.jpg",
    title: "Signal 20 Square Pillow",
    originalPrice: 150,
    salePrice: 75,
    bestSelling: 9,
    date: "2023-09-12",
    available: 20,
    feature: false,
    type: "Home",
  },
  {
    id: "7",
    image: "/image/furniture-07.jpg",
    imageHover: "/image/furniture-07-02.jpg",
    title: "Spot On Table Mirror",
    originalPrice: 160,
    salePrice: 90,
    bestSelling: 4,
    date: "2023-01-25",
    available: 15,
    feature: true,
    type: "Home",
  },
  {
    id: "8",
    image: "/image/furniture-08.jpg",
    imageHover: "/image/furniture-08-02.jpg",
    title: "Longday Bar Cart",
    originalPrice: 210,
    salePrice: 160,
    bestSelling: 2,
    date: "2023-03-30",
    available: 9,
    feature: false,
    type: "Kitchen",
  },
  {
    id: "9",
    image: "/image/furniture-09.jpg",
    imageHover: "/image/furniture-09-02.jpg",
    title: "Offline Outdoor Chair",
    originalPrice: 90,
    salePrice: 86,
    bestSelling: 0,
    date: "2023-02-20",
    available: 10,
    feature: false,
    type: "Kitchen",
  },
  {
    id: "10",
    image: "/image/furniture-11.jpg",
    imageHover: "/image/furniture-11-02.jpg",
    title: "Ester Linen Quilt Set",
    originalPrice: 180,
    salePrice: 140,
    bestSelling: 0,
    date: "2023-03-10",
    available: 7,
    feature: false,
    type: "Kitchen",
  },
  {
    id: "11",
    image: "/image/furniture-12.jpg",
    imageHover: "/image/furniture-12-02.jpg",
    title: "Perch Outdoor Lounge Chair",
    originalPrice: 210,
    salePrice: 160,
    bestSelling: 0,
    date: "2023-04-05",
    available: 5,
    feature: false,
    type: "Office",
  },
  {
    id: "12",
    image: "/image/furniture-13.jpg",
    imageHover: "/image/furniture-13-02.jpg",
    title: "Offline Outdoor Chair",
    originalPrice: 210,
    salePrice: 160,
    bestSelling: 0,
    date: "2023-05-10",
    available: 3,
    feature: false,
    type: "Kitchen",
  },
  {
    id: "13",
    image: "/image/furniture-14.jpg",
    imageHover: "/image/furniture-14-02.jpg",
    title: "Offline Outdoor Chair",
    originalPrice: 210,
    salePrice: 160,
    bestSelling: 0,
    date: "2023-06-01",
    available: 6,
    feature: false,
    type: "Office",
  },
];

export const ProductCollectionData = [
  {
    id: 1,
    image: "/image/furniture-09.jpg",
    imageHover: "/image/furniture-09-02.jpg",
    title: "Offline Outdoor Chair",
    originalPrice: 90,
    salePrice: 86,
    type: "Office",
  },
  {
    id: 2,
    image: "/image/furniture-11.jpg",
    imageHover: "/image/furniture-11-02.jpg",
    title: "Ester Linen Quilt Set",
    originalPrice: 180,
    salePrice: 140,
    type: "Office",
  },
  {
    id: 3,
    image: "/image/furniture-12.jpg",
    imageHover: "/image/furniture-12-02.jpg",
    title: "Perch Outdoor Lounge Chair",
    originalPrice: 210,
    salePrice: 160,
    type: "Office",
  },
  {
    id: 4,
    image: "/image/furniture-13.jpg",
    imageHover: "/image/furniture-13-02.jpg",
    title: "Offline Outdoor Chair",
    originalPrice: 210,
    salePrice: 160,
    type: "Kitchen",
  },
  {
    id: 5,
    image: "/image/furniture-14.jpg",
    imageHover: "/image/furniture-14-02.jpg",
    title: "Offline Outdoor Chair",
    originalPrice: 210,
    salePrice: 160,
    type: "Kitchen",
  },
  {
    id: 6,
    image: "/image/furniture-01.jpg",
    imageHover: "/image/furniture-01-02.jpg",
    title: "Field Lounge Chair",
    originalPrice: 200,
    salePrice: 150,
    type: "Home",
  },
  {
    id: 7,
    image: "/image/furniture-02.jpg",
    imageHover: "/image/furniture-02-02.jpg",
    title: "Peek 1 Door 3 Drawer Credenza",
    originalPrice: 150,
    salePrice: 130,
    type: "Home",
  },
  {
    id: 8,
    image: "/image/furniture-03.jpg",
    imageHover: "/image/furniture-03-02.jpg",
    title: "Bully Table Lamp",
    originalPrice: 350,
    salePrice: 250,
    type: "Home",
  },
  {
    id: 9,
    image: "/image/furniture-04.jpg",
    imageHover: "/image/furniture-04-02.jpg",
    title: "Bobber Table Lamp",
    originalPrice: 350,
    salePrice: 320,
    type: "Home",
  },
  {
    id: 10,
    image: "/image/furniture-05.jpg",
    imageHover: "/image/furniture-05-02.jpg",
    title: "Half Past Large Side Table",
    originalPrice: 200,
    salePrice: 180,
    type: "Home",
  },
  {
    id: 11,
    image: "/image/furniture-06.jpg",
    imageHover: "/image/furniture-06-02.jpg",
    title: "Signal 20 Square Pillow",
    originalPrice: 150,
    salePrice: 75,
    type: "Home",
  },
  {
    id: 12,
    image: "/image/furniture-09.jpg",
    imageHover: "/image/furniture-09-02.jpg",
    title: "Offline Outdoor Chair",
    originalPrice: 90,
    salePrice: 86,
    type: "Kitchen",
  },
  {
    id: 13,
    image: "/image/furniture-11.jpg",
    imageHover: "/image/furniture-11-02.jpg",
    title: "Ester Linen Quilt Set",
    originalPrice: 180,
    salePrice: 140,
    type: "Kitchen",
  },
  {
    id: 14,
    image: "/image/furniture-12.jpg",
    imageHover: "/image/furniture-12-02.jpg",
    title: "Perch Outdoor Lounge Chair",
    originalPrice: 210,
    salePrice: 160,
    type: "Kitchen",
  },
  {
    id: 15,
    image: "/image/furniture-13.jpg",
    imageHover: "/image/furniture-13-02.jpg",
    title: "Offline Outdoor Chair",
    originalPrice: 210,
    salePrice: 160,
    type: "Kitchen",
  },
  {
    id: 16,
    image: "/image/furniture-14.jpg",
    imageHover: "/image/furniture-14-02.jpg",
    title: "Offline Outdoor Chair",
    originalPrice: 210,
    salePrice: 160,
    type: "Kitchen",
  },
];

export const BlogData = [
  {
    id: 1,
    image: "/image/02.jpg",
    day: "March 15, 2024",
    location: "LogicGo Infotech",
    title: "Discovering Grotto: A Journey into Timeless Home Elegance",
    detail:
      "Join us on an exploration of Grotto, where timeless elegance meets home decor. In this blog post, we delve into the rich heritage and craftsmanship behind Grotto's furniture collection. Explore how each piece tells a story of luxury, sophistication, and enduring style. Let Grotto inspire you to create a home that is truly timeless.",
  },
  {
    id: 2,
    image: "/image/03.jpg",
    day: "March 15, 2024",
    location: "LogicGo Infotech",
    title: "Grotto: Crafting Your Signature Style in Home Decor",
    detail:
      "Unlock the secrets of crafting your signature style with Grotto's exquisite home decor. This blog post dives into the art of personalizing your living space, showcasing how Grotto's furniture pieces can serve as the canvas for your unique aesthetic vision. Discover how to infuse personality, elegance, and timeless charm into every corner of your home with Grotto.",
  },
  {
    id: 3,
    image: "/image/04.jpg",
    day: "March 15, 2024",
    location: "LogicGo Infotech",
    title: "The Art of Timeless Living: Grotto's Furniture Masterpieces",
    detail:
      "Embark on a journey through the world of timeless living with Grotto's exquisite furniture masterpieces. In this blog post, we unveil the craftsmanship, elegance, and allure behind each meticulously crafted piece. Explore how Grotto's furniture can elevate your home decor, creating a space that resonates with sophistication and charm for generations to come.",
  },
  {
    id: 4,
    image: "/image/05.jpg",
    day: "March 15, 2024",
    location: "LogicGo Infotech",
    title: "Elevate Your Home: Grotto's Guide to Timeless Interior Design",
    detail:
      "Transform your living space into a sanctuary of style and sophistication with Grotto's expert tips on timeless interior design. Discover how to infuse elegance into every corner of your home, from selecting the perfect furniture pieces to mastering the art of decor arrangement. Let Grotto be your partner in creating a space that stands the test of time.",
  },
  {
    id: 5,
    image: "/image/01.webp",
    day: "March 15, 2024",
    location: "LogicGo Infotech",
    title: "Grotto: Elevating Your Home Decor With Timeless Sophistication",
    detail:
      "Uncover the essence of timeless sophistication with Grotto furniture. This blog post takes you on a journey through the elegance and refinement that define Grotto's signature style. Discover how each meticulously crafted piece can elevate your home decor, infusing it with a sense of luxury and charm that transcends trends. Explore the art of living beautifully with Grotto.",
  },
];

export const LogoBrands = [
  {
    image: "/image/B-02.png",
  },
  {
    image: "/image/B-03.png",
  },
  {
    image: "/image/B-04.png",
  },
  {
    image: "/image/B-05.png",
  },
  {
    image: "/image/B-06.png",
  },
  {
    image: "/image/B-07.png",
  },
];

export const InstagramPostData = [
  {
    image: "/image/in-01.webp",
  },
  {
    image: "/image/in-02.webp",
  },
  {
    image: "/image/in-03.webp",
  },
  {
    image: "/image/in-04.webp",
  },
  {
    image: "/image/in-05.webp",
  },
  {
    image: "/image/in-06.webp",
  },
];

export const CardData = [
  {
    image: "/image/furniture-01.jpg",
    title: "Furniture 1",
  },
  {
    image: "/image/furniture-11.jpg",
    title: "Furniture 2",
  },
  {
    image: "/image/L10-10.jpg",
    title: "Home Page",
  },
  {
    image: "/image/L10-01.jpg",
    title: "Pottery",
  },
];

export const dataEachProduct = [
  {
    image: "/image/furniture-15.jpg",
  },
  {
    image: "/image/furniture-15-02.jpg",
  },
  {
    image: "/image/furniture-15-03.jpg",
  },
  {
    image: "/image/furniture-15-04.jpg",
  },
  {
    image: "/image/furniture-15-05.jpg",
  },
];

export const sidebarLinks = [
  {
    imgURL: "/icon/home.svg",
    route: "/admin/dashboard",
    label: "Home",
  },
  {
    imgURL: "/icon/leaderboard.svg",
    route: "/admin/dashboard/leaderboard",
    label: "Leaderboard",
  },
  {
    imgURL: "/icon/cart.svg",
    route: "/admin/dashboard/orders",
    label: "Order",
  },
  {
    imgURL: "/icon/products-major.svg",
    route: "/admin/dashboard/products",
    label: "Products",
  },
  {
    imgURL: "/icon/messages-3.svg",
    route: "/admin/dashboard/messages",
    label: "Messages",
  },
];
